<a href="https://colab.research.google.com/github/icebearian/Python-machinelearning/blob/main/Lec1_2_IntroToPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Thư viện NumPy**
- NumPy Array
- Array Indexing trong NumPy
- Các thao tác trên Array trong NumPy

In [1]:
import numpy as np

**NumPy Array**

In [2]:
a = np.zeros((2,2))
print(a)
b = np.ones((1,2))
print(b)
c = np.full((2,2),7)
print(c)
d = np.eye(2)
print(d)
e = np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.47758181 0.85625566]
 [0.46489485 0.57904425]]


**Array Indexing**

In [3]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
b = a[:2,1:3]
print(b)
print(a[0,1])
b[0,0] = 77
print(a[0,1])

[[2 3]
 [6 7]]
2
77


In [4]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
row_1 = a[1,:]
row_2 = a[1:2, :]
print(row_1,row_1.shape)
print(row_2,row_2.shape)
col_1 = a[:,1]
col_2 = a[:,2]
print(col_1,col_1.shape)
print(col_2,col_2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[ 3  7 11] (3,)


In [5]:
a = np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])
print(np.array([a[0,0],a[1,1],a[2,0]]))
print(a[[0,0],[1,1]])
print(np.array([a[0,1],a[0,1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [6]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])
print(a)
b = np.array([0,2,0,1])
print(a[np.arange(4),b])
a[np.arange(4),b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [7]:
a = np.array([[1,2],[3,4],[5,6]])
bool_idx = (a > 2)
print(bool_idx)
print(a[bool_idx])
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [8]:
x = np.array([1,2])
print(x.dtype)

x = np.array([1.0,2.0])
print(x.dtype)

x = np.array([1,2], dtype=np.int64)
print(x.dtype)

int64
float64
int64


**Các thao tác trên Array**

In [9]:
x = np.array([[1,2],[3,4]], dtype = np.float64)
y = np.array([[5,6],[7,8]], dtype = np.float64)

print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [12]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(v.dot(w))
print(np.dot(v,w))
print(x.dot(v))
print(np.dot(x,v).shape)
print(x.dot(y))
print(np.dot(x,y))

219
219
[29 67]
(2,)
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [14]:
x = np.array([[1,2,3],[3,4,5]])
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))


18
[4 6 8]
[ 6 12]


In [15]:
x = np.array([[1,2],[3,4]])
print(x)
print(x.T)
v = np.array([[1,2,3]])
print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [17]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([[1,0,1]])
y = np.empty_like(x)
for i in range(4):
  y[i,:] = x[i,:] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [19]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([[1,0,1]])
vv = np.tile(v, (4,1))
print(vv)
vv2 = np.tile(v,(4,2))
print(vv2)
y = x + vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[1 0 1 1 0 1]
 [1 0 1 1 0 1]
 [1 0 1 1 0 1]
 [1 0 1 1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [20]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([[1,0,1]])
print(v+x)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [21]:
v = np.array([1,2,3])
w = np.array([4,5])
x = np.array([[1,2,3],[4,5,6]])
print(x+v)
print((x.T+w).T)
print(x*2)

[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
